/*
 * gf64/gf64_cantor_basis.h — precomputed Cantor basis vectors v_0..v_19
 *   for GF(2^64) with the NIST polynomial x^64 + x^4 + x^3 + x + 1.
 *
 * The Cantor basis satisfies v_0 = 1 and v_{i+1}^2 + v_{i+1} = v_i.
 * These constants were generated by gf64/test/gen_cantor_basis2.c
 * (Artin-Schreier linear-algebra solver with span-checking at each step).
 *
 * Used by gf64_additive_fft_lch14.c for the Lin-Chung-Han (LCH14)
 * additive FFT butterfly: at level i, the multiplier is
 *
 *   mu_j = s_i(v_j) / s_i(v_i)
 *
 * where s_i is the i-th linearized polynomial s_0(x) = x,
 * s_{i+1}(x) = s_i(x)^2 + s_i(x). By the defining property
 * s_i(v_i) = 1, so mu_j = s_i(v_j).
 */

#ifndef GF64_CANTOR_BASIS_H
#define GF64_CANTOR_BASIS_H

#include "gf64_global.h"

#ifdef __cplusplus
extern "C" {
#endif

static const gf64_t GF64_CANTOR_BASIS[20] = {
    0x0000000000000001ULL,  /* v_0 */
    0x19c9369f278adc02ULL,  /* v_1 */
    0xa181e7d66f5ff794ULL,  /* v_2 */
    0x5db84357ce785d08ULL,  /* v_3 */
    0xb973d466f5c9d0caULL,  /* v_4 */
    0x521ac889831a075eULL,  /* v_5 */
    0x033ce8beddc8a656ULL,  /* v_6 */
    0xb5846c4e07b91010ULL,  /* v_7 */
    0x4087b8cbb37a32ecULL,  /* v_8 */
    0x00d0d3888c0ae17cULL,  /* v_9 */
    0xafd5ac70237f2222ULL,  /* v_10 */
    0xe3f5af99cc3aaaf8ULL,  /* v_11 */
    0x5a1db3b16a0b58b8ULL,  /* v_12 */
    0x09947c54fe7ee248ULL,  /* v_13 */
    0x0e8eaf0e0068f544ULL,  /* v_14 */
    0xa2a113500b4b4f5aULL,  /* v_15 */
    0xe96f9805d6ce0bb0ULL,  /* v_16 */
    0x53496f8b5c9edd4cULL,  /* v_17 */
    0xad325cb6f4ac2a9eULL,  /* v_18 */
    0x4a8dcf8bd7ede826ULL,  /* v_19 */
};

#ifdef __cplusplus
}
#endif

#endif /* GF64_CANTOR_BASIS_H */